"use client";
import Link from "next/link";
import { useState } from "react";

// export const metadata = {
//   title: "AuthLayout",
//   description: "Generated by Next.js",
// };

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [input, setInput] = useState("")

  return (
    <>
      <div>
        <input value={input} onChange={(e) => setInput(e.target.value)} />
      </div>
      
      <Link href="/register">register</Link>
      <Link href="/login">login</Link>
      <Link href="/forgot-password">forgot password</Link>

      {children}
    </>
  );
}
