export const metadata = {
  title: "AuthLayout",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <header className="w-full p-6 bg-yellow-300 flex justify-center gap-6">
        <p>home</p>
        <p>about</p>
        <p>product</p>
        <p>features</p>
      </header>
      {children}
    </>
  );
}
