import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="w-full p-6 bg-gray-300 flex justify-center gap-6">
          <p>home</p>
          <p>about</p>
          <p>product</p>
          <p>features</p>
        </header>
        {children}
      </body>
    </html>
  );
}
