import "./globals.css";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    default : "Next js learnig",
    template : "%s | next js",
    absolute : "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="w-full p-6 bg-gray-300 flex justify-center gap-6">
          <Link href="/">Home</Link>
          <Link href="/profile">profile</Link>
          <Link href="/register">register</Link>
          <Link href="/login">login</Link>
          <Link href="/dashboard">dashboard</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
