
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header className="w-full p-6 bg-blue-300 flex justify-center gap-6">
        <p>home</p>
        <p>about</p>
        <p>product</p>
        <p>features</p>
      </header>
      <body>{children}</body>
    </html>
  );
}
