import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "profile",
    template: "%s | next js",
    absolute: "",
  },
  description: "Generated by Next.js",
};

export default function Profile() {
  return (
    <>
      <div>Profile Page</div>
      <Link href="/articles/breking-news-123?lang=en">Read in english</Link>
      <Link href="/articles/breking-news-123?lang=bn">Read in bangla</Link>
    </>
  );
}